# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-05-28 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_auto_20240703_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='execution_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='время выполнения (сек)'),
        ),
        migrations.AddField(
            model_name='solution',
            name='too_fast',
            field=models.BooleanField(default=False, verbose_name='слишком быстрое решение'),
        ),
    ]
