# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-05-28 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_auto_20250528_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='execution_time',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='время выполнения (сек)'),
        ),
    ]
