# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-05-28 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_draft_execution_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft',
            name='execution_time',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='execution_time',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='too_fast',
        ),
    ]
