# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-05-29 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_auto_20250528_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='needs_manual_check',
            field=models.BooleanField(default=False, verbose_name='требуется ручная проверка (слишком быстро)'),
        ),
        migrations.AddField(
            model_name='solution',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Когда студент впервые открыл задание', null=True, verbose_name='время начала работы'),
        ),
        migrations.AddField(
            model_name='solution',
            name='time_spent',
            field=models.FloatField(blank=True, help_text='Общее время, потраченное на выполнение', null=True, verbose_name='время выполнения (в секундах)'),
        ),
    ]
