# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-05-29 11:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_auto_20250529_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='min_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=60), help_text='Если задание решено быстрее этого времени — появляется знак "?"', verbose_name='минимальное время выполнения'),
        ),
    ]
