# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-05-29 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_task_min_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='time_spent',
            field=models.FloatField(blank=True, help_text='накопленное время выполнения (в секундах)', null=True),
        ),
    ]
