# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-05-31 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_draft_time_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='needs_manual_check',
            field=models.BooleanField(default=False, verbose_name='Слишком быстрое решение'),
        ),
    ]
